export const corridors = [
  {
    slug: "johannesburg-to-durban",
    from: "johannesburg",
    to: "durban",
    title: "Johannesburg → Durban",
    route: "N3",
    km: 585,
    drive: "≈ 8 h",
    transit: "24 h",
    band: "Next day",
    tolls: "N3 toll plazas between the Vaal and Durban (class-dependent rates).",
    departures: "Daily line-haul, with overnight departures for morning delivery in Durban.",
    stops: ["Vaal Plaza", "Harrismith", "Tugela Plaza", "Marianhill"],
    highlights: [
      "Busiest freight corridor in South Africa — book departures early in peak season.",
      "Van Reenen's Pass is the pinch point: steep gradients, winter fog and occasional closures after storms.",
      "Chain licences, load security and strapping checks are done before the pass, not on it.",
      "Port congestion in Durban can add hours; we confirm collection windows with the terminal first.",
    ],
    best: "Overnight departures give you a morning delivery window and miss N3 peak traffic through Ladysmith.",
    faqs: [
      { q: "Can you collect in Johannesburg and deliver to the Durban port terminals?", a: "Yes. We collect from Gauteng depots, factories and side streets and deliver directly into Durban container and conventional terminals, or to your consignee in the greater Durban area." },
      { q: "How long should I allow for a Durban delivery before cut-off?", a: "Allow a full working day between collection in Gauteng and terminal cut-off. Weather on Van Reenen's Pass and terminal queues are the two variables we cannot compress." },
    ],
  },
  {
    slug: "johannesburg-to-cape-town",
    from: "johannesburg",
    to: "cape-town",
    title: "Johannesburg → Cape Town",
    route: "N1",
    km: 1400,
    drive: "≈ 17 h",
    transit: "48 h",
    band: "2 days",
    tolls: "Four mainline plazas on the N1 (Grasmere, Vaal, Verkeerdevlei and Huguenot) plus ramp tolls.",
    departures: "Scheduled departures Sunday to Wednesday for mid-week delivery.",
    stops: ["Bloemfontein", "Colesberg", "Beaufort West", "Worcester"],
    highlights: [
      "The longest scheduled run on our network — always planned as a two-day transit with a driver change or rest stop.",
      "The Beaufort West to Colesberg stretch is long, hot and empty: fuel and tyres are checked before departure.",
      "Huguenot Tunnel and the Hex River Pass bring winter delays when snow or ice closes the N1.",
      "Cape Town deliveries are booked against a slot so the truck does not arrive during the morning peak.",
    ],
    best: "Depart after the afternoon peak in Gauteng; the truck crosses the Free State overnight and delivers on day two.",
    faqs: [
      { q: "Is a part load viable on this route?", a: "Yes. We run regular consolidation departures on the N1, so a few pallets can travel at part-load rates with the same tracking and proof of delivery." },
      { q: "Do you handle cross-docking in Bloemfontein?", a: "Cross-docking and consolidation can be arranged in Bloemfontein where it shortens the second leg — ask for it when you request a quote." },
    ],
  },
  {
    slug: "johannesburg-to-bloemfontein",
    from: "johannesburg",
    to: "bloemfontein",
    title: "Johannesburg → Bloemfontein",
    route: "N1",
    km: 400,
    drive: "≈ 5 h",
    transit: "Same / next day",
    band: "1 day",
    tolls: "Grasmere and Vaal plazas on the N1 south.",
    departures: "Morning departures for same-day delivery; afternoon departures for next-morning.",
    stops: ["Vaal Plaza", "Kroonstad", "Verkeerdevlei"],
    highlights: [
      "Close enough for same-day delivery when loading finishes before midday.",
      "Free State weather is the main risk: hail and fog on the N1 between Kroonstad and Bloemfontein.",
      "A natural consolidation point for onward loads to the Eastern Cape and Lesotho.",
    ],
    best: "Load before 10:00 for a same-day delivery; anything later travels overnight and lands the next morning.",
    faqs: [
      { q: "Can you carry abnormal or oversize loads on this route?", a: "Oversize and abnormal loads require permits and escort arrangements. Share dimensions and weights and we will confirm what is possible before you book." },
    ],
  },
  {
    slug: "johannesburg-to-polokwane",
    from: "johannesburg",
    to: "polokwane",
    title: "Johannesburg → Polokwane",
    route: "N1",
    km: 295,
    drive: "≈ 4 h",
    transit: "Same day",
    band: "Same day",
    tolls: "No mainline toll on this section.",
    departures: "Twice-daily departures, plus same-day courier options for urgent freight.",
    stops: ["Middelburg", "Belfast", "Zebediela"],
    highlights: [
      "A same-day corridor for retail, agri and mining supply into Limpopo.",
      "Through Tzaneen and the platinum belt with multi-drop routes available.",
      "Border traffic on the N1 near Musina can back up; we track it when your load continues north.",
    ],
    best: "Morning collection means afternoon delivery; anything after 14:00 lands the next morning.",
    faqs: [
      { q: "Do you deliver beyond Polokwane to the border?", a: "Yes — Musina and Beit Bridge are served daily on the same N1 run, with cross-border loads handled through our clearing partners." },
    ],
  },
  {
    slug: "cape-town-to-gqeberha",
    from: "cape-town",
    to: "gqeberha",
    title: "Cape Town → Gqeberha",
    route: "N2",
    km: 750,
    drive: "≈ 9 h",
    transit: "24–36 h",
    band: "1–2 days",
    tolls: "No mainline toll on the N2 through the Garden Route.",
    departures: "Four departures a week, plus part-load consolidation.",
    stops: ["Worcester", "George", "Jeffreys Bay"],
    highlights: [
      "The Garden Route section is scenic but narrow — weather and weekend traffic set the pace.",
      "Good option for part loads, since the corridor consolidates well.",
      "Eastern Cape port volumes need slot confirmations; we book collection windows in advance.",
    ],
    best: "Leave Cape Town in the late afternoon to clear the Winelands peak and deliver the next morning.",
    faqs: [
      { q: "Can freight move in both directions on this corridor?", a: "Yes. We run both legs, so return loads from Gqeberha and East London to the Cape are quoted competitively." },
    ],
  },
  {
    slug: "johannesburg-to-gaborone",
    from: "johannesburg",
    to: "gaborone",
    title: "Johannesburg → Gaborone",
    route: "N14 / A1",
    km: 380,
    drive: "≈ 5 h",
    transit: "2–3 days",
    band: "Cross-border",
    tolls: "No mainline toll on the N14 to the Tlokweng border post.",
    departures: "Scheduled cross-border departures with cleared documentation prepared before collection.",
    stops: ["Rustenburg", "Zeerust", "Tlokweng / Kopfontein"],
    highlights: [
      "Cross-border loads travel with a SADC Certificate of Origin, commercial invoice, packing list and bill of lading.",
      "We use licensed clearing agents at the border — the truck should not wait on paperwork.",
      "Vehicle papers, PRDP and driver documentation are checked before departure, not at the port of entry.",
      "Customs duties and VAT in Botswana are for the importer's account unless agreed otherwise.",
    ],
    best: "Clear early in the week: border posts and Botswana customs slow down on Fridays and public holidays.",
    faqs: [
      { q: "Who handles the customs paperwork?", a: "Our clearing partner prepares and lodges the entry; you supply the commercial documents and importer details in good time before collection." },
      { q: "Can you deliver anywhere in Botswana?", a: "Yes — Gaborone, Francistown and industrial areas on the Trans-Kalahari corridor are all reachable from this run." },
    ],
  },
];

export const getCorridor = (slug) => corridors.find((c) => c.slug === slug);
