export const services = [
 { slug: "long-distance-haulage", title: "Long-distance haulage", short: "Full national coverage between Johannesburg, Durban, Cape Town, Gqeberha and everything on the N1, N2, N3 and N4.",
   intro: "Reliable inter-city freight with planned departures, tracked trucks and drivers who know the routes.", pts: ["Scheduled departures on the main national corridors", "Live vehicle tracking and proactive delay updates", "Experienced, vetted long-haul drivers", "Proof of delivery sent the same day"] },
 { slug: "short-distance-delivery", title: "Short-distance & local delivery", short: "Collections and drop-offs within and between nearby towns and metros, same-day where possible.",
   intro: "Fast, flexible regional runs for businesses that need goods moved between depots, stores and customers.", pts: ["Same-day and next-day regional delivery", "Flexible collection windows", "Multi-drop routes for retail and distribution", "Direct line to your dispatcher"] },
 { slug: "full-truck-loads", title: "Full truck loads", short: "A dedicated truck for your cargo, collected and delivered without stops in between.",
   intro: "When your freight fills a vehicle, a dedicated truck is the fastest and safest way to move it.", pts: ["Door-to-door with no cargo mixing", "Choice of vehicle size for your load", "Fixed pricing per trip", "Ideal for pallets, bulk goods and machinery"] },
 { slug: "part-loads", title: "Part loads", short: "Share truck space and pay only for what you ship.",
   intro: "Not enough cargo for a full truck? Part loads let you ship regularly without paying for empty space.", pts: ["Pay by pallet, weight or volume", "Regular weekly consolidation runs", "Lower cost than a dedicated truck", "Same tracking and proof of delivery"] }];
export const posts = [
 { slug: "full-load-or-part-load", date: "2026-09-18", title: "Full load or part load: how to choose", excerpt: "A simple way to decide which option saves you money without risking your delivery date.",
   body: ["A full truck load (FTL) gives you a whole vehicle for your cargo. It is usually faster and carries less handling risk because nothing else is loaded or unloaded along the way.", "A part load (LTL) shares space with other customers' freight. You pay only for the space you use, which suits smaller or regular shipments, but transit can take longer because of consolidation.", "As a rule, if your cargo is close to filling a truck or is time-critical, price a full load. If you ship a few pallets and have some flexibility, a part load is often cheaper.", "Ask your carrier to quote both. The difference is sometimes smaller than you expect."] },
 { slug: "getting-an-accurate-freight-quote", date: "2026-09-04", title: "How to get an accurate freight quote the first time", excerpt: "The seven details every carrier needs to price your load properly.",
   body: ["Quotes change when details change. Give the carrier the full picture up front: collection and delivery addresses, cargo type, weight, dimensions, number of pallets, and your required delivery date.", "Mention access constraints. Narrow gates, loading docks, forklift availability and site opening hours all affect which vehicle can be used and how long loading takes.", "Tell them about special handling, such as fragile goods, stacking limits or high-value cargo, so insurance and packing are agreed before collection.", "Finally, share your expected monthly volume. Regular shippers can often secure better rates and priority scheduling."] },
 { slug: "planning-long-distance-deliveries", date: "2026-08-21", title: "Planning long-distance deliveries across South Africa", excerpt: "Practical ways to build delay buffers into inter-city freight.",
   body: ["Long-distance transit times depend on more than kilometres. Driver rest rules, toll and weighbridge stops, weather and roadworks can all add hours.", "Build a buffer into your schedule for time-critical shipments, and avoid promising customers a delivery to the hour.", "Choose a carrier that tracks vehicles and tells you about delays early. An early warning gives you time to adjust, which is usually worth more than a slightly lower rate.", "Book regular routes in advance where possible. Planned departures are easier to keep on time than last-minute loads."] }];
export const branches = [{ name: "Head office, Johannesburg", addr: "Add street address, Johannesburg, Gauteng", phone: "+27 11 000 0000" }];
export const hours = [["Monday to Friday", "06:00 – 18:00"], ["Saturday", "07:00 – 13:00"], ["Sunday & public holidays", "Closed (WhatsApp monitored)"]];
