export const vehicles = [
  {
    key: "panel-van",
    type: "Panel van & bakkie",
    payload: "1 – 1.5 t",
    volume: "6 – 10 m³",
    pallets: "2 – 4 Euro",
    spec: { payloadT: 1.5, volumeM3: 8, palletsN: 4 },
    best: "Documents, spares, samples and urgent small freight",
    notes: "No tail lift on most units; kerbside collection only.",
  },
  {
    key: "3-ton",
    type: "3-ton rigid",
    payload: "3 t",
    volume: "15 – 18 m³",
    pallets: "6 – 8 Euro",
    spec: { payloadT: 3, volumeM3: 16, palletsN: 8 },
    best: "Retail replenishment and multi-drop rounds",
    notes: "Fits under most loading docks and basement height limits.",
  },
  {
    key: "4-ton",
    type: "4-ton rigid",
    payload: "4 t",
    volume: "20 m³",
    pallets: "8 – 10 Euro",
    spec: { payloadT: 4, volumeM3: 20, palletsN: 10 },
    best: "General cargo, packaged goods, light industrial",
    notes: "Workhorse of local distribution — available with a tail lift.",
  },
  {
    key: "8-ton",
    type: "8-ton rigid",
    payload: "8 t",
    volume: "34 – 40 m³",
    pallets: "14 – 16 Euro",
    spec: { payloadT: 8, volumeM3: 36, palletsN: 16 },
    best: "Regional runs between metros",
    notes: "Requires a heavier licence class and route clearance for some urban areas.",
  },
  {
    key: "10-ton",
    type: "10-ton rigid",
    payload: "10 t",
    volume: "45 m³",
    pallets: "18 – 20 Euro",
    spec: { payloadT: 10, volumeM3: 45, palletsN: 20 },
    best: "Mid-size loads that do not fill a trailer",
    notes: "Good compromise when part loads are close to a full trailer.",
  },
  {
    key: "tautliner",
    type: "13.6 m curtainsider (tautliner)",
    payload: "24 – 26 t",
    volume: "86 – 96 m³",
    pallets: "26 industrial (1200×1000) or 34 Euro (1200×800)",
    spec: { payloadT: 25, volumeM3: 90, palletsN: 34 },
    best: "Full truck loads on national corridors",
    notes: "Side loading and twin rear doors; the standard for palletised freight.",
  },
  {
    key: "super-link",
    type: "Super Link (two trailers)",
    payload: "28 – 34 t",
    volume: "110 – 120 m³",
    pallets: "38 – 42 Euro",
    spec: { payloadT: 30, volumeM3: 115, palletsN: 42 },
    best: "High-volume loads on main corridors",
    notes: "Higher mass needs route and bridge clearance checks before dispatch.",
  },
  {
    key: "flatbed",
    type: "Flatbed & step deck",
    payload: "25 – 28 t",
    volume: "Open deck",
    pallets: "8 – 12 + oversize",
    spec: { payloadT: 26, volumeM3: 0, palletsN: 12 },
    best: "Steel, timber, machinery and oversize cargo",
    notes: "Load security equipment (chains, straps, winches) travels with the truck.",
  },
  {
    key: "side-tipper",
    type: "Side-tipper & bulk tautliner",
    payload: "30 – 35 t",
    volume: "Bulk",
    pallets: "Loose material",
    spec: { payloadT: 32, volumeM3: 0, palletsN: 0 },
    best: "Aggregate, sand, coal, grain and other bulk",
    notes: "Tipping permitted only at sites with a prepared hardstanding.",
  },
  {
    key: "container-20",
    type: "20-ft container on a truck",
    payload: "26 – 28 t",
    volume: "33 m³",
    pallets: "10 Euro",
    spec: { payloadT: 26, volumeM3: 33, palletsN: 10 },
    best: "Port-to-door import and export containers",
    notes: "Collected at Durban, Cape Town and Ngqura terminals with slot bookings.",
  },
  {
    key: "container-40",
    type: "40-ft container on a truck",
    payload: "24 – 26 t",
    volume: "67 m³",
    pallets: "20 – 21 Euro",
    spec: { payloadT: 24, volumeM3: 67, palletsN: 21 },
    best: "Full container loads and containerised exports",
    notes: "High-cube and reefer units available on request.",
  },
  {
    key: "reefer",
    type: "Refrigerated trailer",
    payload: "22 – 25 t",
    volume: "80 – 86 m³",
    pallets: "26 industrial",
    spec: { payloadT: 22, volumeM3: 82, palletsN: 26 },
    best: "Chilled and frozen goods, produce and dairy",
    notes: "Temperature set points recorded and sent with the proof of delivery.",
  },
];

export const vehicleNotes = [
  "Legal payload depends on axle configuration, licence and route mass limits — always confirm per load.",
  "Pallet counts are single-deck and assume standard deck space with no double stacking.",
  "Aisles, dunnage and load bars reduce usable pallet positions; tell us if your cargo needs them.",
];

export const palletArea = { euro: 0.96, industrial: 1.2 };
